### ISSUE TITLE
Documentation Meta

### ISSUE THREAD

**Issue by erichte-ibm** [erichte-ibm/skiboot#19]
List the Documentation Items here

- [ ] #20 Document Generic Backend Interface
- [ ] #21 Document Generic Storage Driver Interface
- [ ] #22 Document edk2 driver specifics
- [ ] #23 Document secboot_tpm driver specifics
- [ ] #24 Document Platform specific config/enablement
